# Generated by Django 4.2.1 on 2023-05-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(editable=False, max_length=256, unique=True)),
                ('access_token', models.CharField(editable=False, max_length=256, unique=True)),
                ('user_uuid', models.CharField(editable=False, max_length=256, unique=True)),
            ],
        ),
    ]
